[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "langchain-medical-rag"
version = "0.1.0"
description = "A medical RAG and image segmentation pipeline for dermatological analysis."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymupdf",
    "langchain",
    "langchain-community",
    "langchain-core",
    "langgraph",
    "faiss-cpu",
    "langchain_openai",
    "sentence-transformers",
    "pydantic",
    "pydantic-settings",
    "torch",
    "torchvision",
    "pillow",
    "pandas",
    "scikit-learn",
    "typer",
    "python-dotenv"
]

[project.scripts]
medical-rag = "app.cli.main:app"

[tool.setuptools.packages.find]
where = ["src"]
